<%@ taglib uri = "http://java.sun.com/jsp/jstl/core" prefix = "c"%>
<%@ page isELIgnored="false" %>

<!DOCTYPE html>
<html>
<head>
    <title>Superheroes</title>
    <style><%@include file="../css/style.css"%></style>
</head>
<body>
<hr>

    <h1> Select a Superhero </h1>
    <form method="get" action="/get/">
        <select name="id">
            <option value="1">A-Bomb</option>
            <option value="2">Abe Sapien</option>
            <option value="3">Abin Sur</option>
            <option value="4">Abomination</option>
            <option value="5">Abraxas</option>
            <option value="6">Absorbing Man</option>
            <option value="7">Adam Monroe</option>
            <option value="8">Adam Strange</option>
            <option value="9">Agent 13</option>
            <option value="10">Agent Bob</option>
            <option value="11">Agent Zero</option>
            <option value="12">Air-Walker</option>
            <option value="13">Ajax</option>
            <option value="14">Alan Scott</option>
            <option value="15">Alex Mercer</option>
            <option value="16">Alex Woolsly</option>
            <option value="17">Alfred Pennyworth</option>
            <option value="18">Alien</option>
            <option value="19">Allan Quatermain</option>
            <option value="20">Amazo</option>
            <option value="21">Ammo</option>
            <option value="22">Ando Masahashi</option>
            <option value="23">Angel</option>
            <option value="24">Angel</option>
            <option value="25">Angel Dust</option>
            <option value="26">Angel Salvadore</option>
            <option value="27">Angela</option>
            <option value="28">Animal Man</option>
            <option value="29">Annihilus</option>
            <option value="30">Ant-Man</option>
            <option value="31">Ant-Man II</option>
            <option value="32">Anti-Monitor</option>
            <option value="33">Anti-Spawn</option>
            <option value="34">Anti-Venom</option>
            <option value="35">Apocalypse</option>
            <option value="36">Aquababy</option>
            <option value="37">Aqualad</option>
            <option value="38">Aquaman</option>
            <option value="39">Arachne</option>
            <option value="40">Archangel</option>
            <option value="41">Arclight</option>
            <option value="42">Ardina</option>
            <option value="43">Ares</option>
            <option value="44">Ariel</option>
            <option value="45">Armor</option>
            <option value="46">Arsenal</option>
            <option value="47">Astro Boy</option>
            <option value="48">Atlas</option>
            <option value="49">Atlas</option>
            <option value="50">Atom</option>
            <option value="51">Atom</option>
            <option value="52">Atom Girl</option>
            <option value="53">Atom II</option>
            <option value="54">Atom III</option>
            <option value="55">Atom IV</option>
            <option value="56">Aurora</option>
            <option value="57">Azazel</option>
            <option value="58">Azrael</option>
            <option value="59">Aztar</option>
            <option value="60">Bane</option>
            <option value="61">Banshee</option>
            <option value="62">Bantam</option>
            <option value="63">Batgirl</option>
            <option value="64">Batgirl</option>
            <option value="65">Batgirl III</option>
            <option value="66">Batgirl IV</option>
            <option value="67">Batgirl V</option>
            <option value="68">Batgirl VI</option>
            <option value="69">Batman</option>
            <option value="70">Batman</option>
            <option value="71">Batman II</option>
            <option value="72">Battlestar</option>
            <option value="73">Batwoman V</option>
            <option value="74">Beak</option>
            <option value="75">Beast</option>
            <option value="76">Beast Boy</option>
            <option value="77">Beetle</option>
            <option value="78">Ben 10</option>
            <option value="79">Beta Ray Bill</option>
            <option value="80">Beyonder</option>
            <option value="81">Big Barda</option>
            <option value="82">Big Daddy</option>
            <option value="83">Big Man</option>
            <option value="84">Bill Harken</option>
            <option value="85">Billy Kincaid</option>
            <option value="86">Binary</option>
            <option value="87">Bionic Woman</option>
            <option value="88">Bird-Brain</option>
            <option value="89">Bird-Man</option>
            <option value="90">Bird-Man II</option>
            <option value="91">Birdman</option>
            <option value="92">Bishop</option>
            <option value="93">Bizarro</option>
            <option value="94">Black Abbott</option>
            <option value="95">Black Adam</option>
            <option value="96">Black Bolt</option>
            <option value="97">Black Canary</option>
            <option value="98">Black Canary</option>
            <option value="99">Black Cat</option>
            <option value="100">Black Flash</option>
            <option value="101">Black Goliath</option>
            <option value="102">Black Knight III</option>
            <option value="103">Black Lightning</option>
            <option value="104">Black Mamba</option>
            <option value="105">Black Manta</option>
            <option value="106">Black Panther</option>
            <option value="107">Black Widow</option>
            <option value="108">Black Widow II</option>
            <option value="109">Blackout</option>
            <option value="110">Blackwing</option>
            <option value="111">Blackwulf</option>
            <option value="112">Blade</option>
            <option value="113">Blaquesmith</option>
            <option value="114">Bling!</option>
            <option value="115">Blink</option>
            <option value="116">Blizzard</option>
            <option value="117">Blizzard</option>
            <option value="118">Blizzard II</option>
            <option value="119">Blob</option>
            <option value="120">Bloodaxe</option>
            <option value="121">Bloodhawk</option>
            <option value="122">Bloodwraith</option>
            <option value="123">Blue Beetle</option>
            <option value="124">Blue Beetle</option>
            <option value="125">Blue Beetle II</option>
            <option value="126">Blue Beetle III</option>
            <option value="127">Boba Fett</option>
            <option value="128">Bolt</option>
            <option value="129">Bomb Queen</option>
            <option value="130">Boom-Boom</option>
            <option value="131">Boomer</option>
            <option value="132">Booster Gold</option>
            <option value="133">Box</option>
            <option value="134">Box III</option>
            <option value="135">Box IV</option>
            <option value="136">Brainiac</option>
            <option value="137">Brainiac 5</option>
            <option value="138">Brother Voodoo</option>
            <option value="139">Brundlefly</option>
            <option value="140">Buffy</option>
            <option value="141">Bullseye</option>
            <option value="142">Bumblebee</option>
            <option value="143">Bumbleboy</option>
            <option value="144">Bushido</option>
            <option value="145">Cable</option>
            <option value="146">Callisto</option>
            <option value="147">Cameron Hicks</option>
            <option value="148">Cannonball</option>
            <option value="149">Captain America</option>
            <option value="150">Captain Atom</option>
            <option value="151">Captain Britain</option>
            <option value="152">Captain Cold</option>
            <option value="153">Captain Epic</option>
            <option value="154">Captain Hindsight</option>
            <option value="155">Captain Mar-vell</option>
            <option value="156">Captain Marvel</option>
            <option value="157">Captain Marvel</option>
            <option value="158">Captain Marvel II</option>
            <option value="159">Captain Midnight</option>
            <option value="160">Captain Planet</option>
            <option value="161">Captain Universe</option>
            <option value="162">Carnage</option>
            <option value="163">Cat</option>
            <option value="164">Cat II</option>
            <option value="165">Catwoman</option>
            <option value="166">Cecilia Reyes</option>
            <option value="167">Century</option>
            <option value="168">Cerebra</option>
            <option value="169">Chamber</option>
            <option value="170">Chameleon</option>
            <option value="171">Changeling</option>
            <option value="172">Cheetah</option>
            <option value="173">Cheetah II</option>
            <option value="174">Cheetah III</option>
            <option value="175">Chromos</option>
            <option value="176">Chuck Norris</option>
            <option value="177">Citizen Steel</option>
            <option value="178">Claire Bennet</option>
            <option value="179">Clea</option>
            <option value="180">Cloak</option>
            <option value="181">Clock King</option>
            <option value="182">Cogliostro</option>
            <option value="183">Colin Wagner</option>
            <option value="184">Colossal Boy</option>
            <option value="185">Colossus</option>
            <option value="186">Copycat</option>
            <option value="187">Corsair</option>
            <option value="188">Cottonmouth</option>
            <option value="189">Crimson Crusader</option>
            <option value="190">Crimson Dynamo</option>
            <option value="191">Crystal</option>
            <option value="192">Curse</option>
            <option value="193">Cy-Gor</option>
            <option value="194">Cyborg</option>
            <option value="195">Cyborg Superman</option>
            <option value="196">Cyclops</option>
            <option value="197">Cypher</option>
            <option value="198">Dagger</option>
            <option value="199">Danny Cooper</option>
            <option value="200">Daphne Powell</option>
            <option value="201">Daredevil</option>
            <option value="202">Darkhawk</option>
            <option value="203">Darkman</option>
            <option value="204">Darkseid</option>
            <option value="205">Darkside</option>
            <option value="206">Darkstar</option>
            <option value="207">Darth Maul</option>
            <option value="208">Darth Vader</option>
            <option value="209">Dash</option>
            <option value="210">Data</option>
            <option value="211">Dazzler</option>
            <option value="212">Deadman</option>
            <option value="213">Deadpool</option>
            <option value="214">Deadshot</option>
            <option value="215">Deathlok</option>
            <option value="216">Deathstroke</option>
            <option value="217">Demogoblin</option>
            <option value="218">Destroyer</option>
            <option value="219">Diamondback</option>
            <option value="220">DL Hawkins</option>
            <option value="221">Doc Samson</option>
            <option value="222">Doctor Doom</option>
            <option value="223">Doctor Doom II</option>
            <option value="224">Doctor Fate</option>
            <option value="225">Doctor Octopus</option>
            <option value="226">Doctor Strange</option>
            <option value="227">Domino</option>
            <option value="228">Donatello</option>
            <option value="229">Donna Troy</option>
            <option value="230">Doomsday</option>
            <option value="231">Doppelganger</option>
            <option value="232">Dormammu</option>
            <option value="233">Dr Manhattan</option>
            <option value="234">Drax the Destroyer</option>
            <option value="235">Ego</option>
            <option value="236">Elastigirl</option>
            <option value="237">Electro</option>
            <option value="238">Elektra</option>
            <option value="239">Elle Bishop</option>
            <option value="240">Elongated Man</option>
            <option value="241">Emma Frost</option>
            <option value="242">Enchantress</option>
            <option value="243">Energy</option>
            <option value="244">ERG-1</option>
            <option value="245">Ethan Hunt</option>
            <option value="246">Etrigan</option>
            <option value="247">Evil Deadpool</option>
            <option value="248">Evilhawk</option>
            <option value="249">Exodus</option>
            <option value="250">Fabian Cortez</option>
            <option value="251">Falcon</option>
            <option value="252">Fallen One II</option>
            <option value="253">Faora</option>
            <option value="254">Feral</option>
            <option value="255">Fighting Spirit</option>
            <option value="256">Fin Fang Foom</option>
            <option value="257">Firebird</option>
            <option value="258">Firelord</option>
            <option value="259">Firestar</option>
            <option value="260">Firestorm</option>
            <option value="261">Firestorm</option>
            <option value="262">Fixer</option>
            <option value="263">Flash</option>
            <option value="264">Flash Gordon</option>
            <option value="265">Flash II</option>
            <option value="266">Flash III</option>
            <option value="267">Flash IV</option>
            <option value="268">Forge</option>
            <option value="269">Franklin Richards</option>
            <option value="270">Franklin Storm</option>
            <option value="271">Frenzy</option>
            <option value="272">Frigga</option>
            <option value="273">Galactus</option>
            <option value="274">Gambit</option>
            <option value="275">Gamora</option>
            <option value="276">Garbage Man</option>
            <option value="277">Gary Bell</option>
            <option value="278">General Zod</option>
            <option value="279">Genesis</option>
            <option value="280">Ghost Rider</option>
            <option value="281">Ghost Rider II</option>
            <option value="282">Giant-Man</option>
            <option value="283">Giant-Man II</option>
            <option value="284">Giganta</option>
            <option value="285">Gladiator</option>
            <option value="286">Goblin Queen</option>
            <option value="287">Godzilla</option>
            <option value="288">Gog</option>
            <option value="289">Goku</option>
            <option value="290">Goliath</option>
            <option value="291">Goliath</option>
            <option value="292">Goliath</option>
            <option value="293">Goliath IV</option>
            <option value="294">Gorilla Grodd</option>
            <option value="295">Granny Goodness</option>
            <option value="296">Gravity</option>
            <option value="297">Greedo</option>
            <option value="298">Green Arrow</option>
            <option value="299">Green Goblin</option>
            <option value="300">Green Goblin II</option>
            <option value="301">Green Goblin III</option>
            <option value="302">Green Goblin IV</option>
            <option value="303">Groot</option>
            <option value="304">Guardian</option>
            <option value="305">Guy Gardner</option>
            <option value="306">Hal Jordan</option>
            <option value="307">Han Solo</option>
            <option value="308">Hancock</option>
            <option value="309">Harley Quinn</option>
            <option value="310">Harry Potter</option>
            <option value="311">Havok</option>
            <option value="312">Hawk</option>
            <option value="313">Hawkeye</option>
            <option value="314">Hawkeye II</option>
            <option value="315">Hawkgirl</option>
            <option value="316">Hawkman</option>
            <option value="317">Hawkwoman</option>
            <option value="318">Hawkwoman II</option>
            <option value="319">Hawkwoman III</option>
            <option value="320">Heat Wave</option>
            <option value="321">Hela</option>
            <option value="322">Hellboy</option>
            <option value="323">Hellcat</option>
            <option value="324">Hellstorm</option>
            <option value="325">Hercules</option>
            <option value="326">Hiro Nakamura</option>
            <option value="327">Hit-Girl</option>
            <option value="328">Hobgoblin</option>
            <option value="329">Hollow</option>
            <option value="330">Hope Summers</option>
            <option value="331">Howard the Duck</option>
            <option value="332">Hulk</option>
            <option value="333">Human Torch</option>
            <option value="334">Huntress</option>
            <option value="335">Husk</option>
            <option value="336">Hybrid</option>
            <option value="337">Hydro-Man</option>
            <option value="338">Hyperion</option>
            <option value="339">Iceman</option>
            <option value="340">Impulse</option>
            <option value="341">Indiana Jones</option>
            <option value="342">Indigo</option>
            <option value="343">Ink</option>
            <option value="344">Invisible Woman</option>
            <option value="345">Iron Fist</option>
            <option value="346">Iron Man</option>
            <option value="347">Iron Monger</option>
            <option value="348">Isis</option>
            <option value="349">Jack Bauer</option>
            <option value="350">Jack of Hearts</option>
            <option value="351">Jack-Jack</option>
            <option value="352">James Bond</option>
            <option value="353">James T. Kirk</option>
            <option value="354">Jar Jar Binks</option>
            <option value="355">Jason Bourne</option>
            <option value="356">Jean Grey</option>
            <option value="357">Jean-Luc Picard</option>
            <option value="358">Jennifer Kale</option>
            <option value="359">Jesse Quick</option>
            <option value="360">Jessica Cruz</option>
            <option value="361">Jessica Jones</option>
            <option value="362">Jessica Sanders</option>
            <option value="363">Jigsaw</option>
            <option value="364">Jim Powell</option>
            <option value="365">JJ Powell</option>
            <option value="366">Johann Krauss</option>
            <option value="367">John Constantine</option>
            <option value="368">John Stewart</option>
            <option value="369">John Wraith</option>
            <option value="370">Joker</option>
            <option value="371">Jolt</option>
            <option value="372">Jubilee</option>
            <option value="373">Judge Dredd</option>
            <option value="374">Juggernaut</option>
            <option value="375">Junkpile</option>
            <option value="376">Justice</option>
            <option value="377">Jyn Erso</option>
            <option value="378">K-2SO</option>
            <option value="379">Kang</option>
            <option value="380">Kathryn Janeway</option>
            <option value="381">Katniss Everdeen</option>
            <option value="382">Kevin 11</option>
            <option value="383">Kick-Ass</option>
            <option value="384">Kid Flash</option>
            <option value="385">Kid Flash II</option>
            <option value="386">Killer Croc</option>
            <option value="387">Killer Frost</option>
            <option value="388">Kilowog</option>
            <option value="389">King Kong</option>
            <option value="390">King Shark</option>
            <option value="391">Kingpin</option>
            <option value="392">Klaw</option>
            <option value="393">Kool-Aid Man</option>
            <option value="394">Kraven II</option>
            <option value="395">Kraven the Hunter</option>
            <option value="396">Krypto</option>
            <option value="397">Kyle Rayner</option>
            <option value="398">Kylo Ren</option>
            <option value="399">Lady Bullseye</option>
            <option value="400">Lady Deathstrike</option>
            <option value="401">Leader</option>
            <option value="402">Leech</option>
            <option value="403">Legion</option>
            <option value="404">Leonardo</option>
            <option value="405">Lex Luthor</option>
            <option value="406">Light Lass</option>
            <option value="407">Lightning Lad</option>
            <option value="408">Lightning Lord</option>
            <option value="409">Living Brain</option>
            <option value="410">Living Tribunal</option>
            <option value="411">Liz Sherman</option>
            <option value="412">Lizard</option>
            <option value="413">Lobo</option>
            <option value="414">Loki</option>
            <option value="415">Longshot</option>
            <option value="416">Luke Cage</option>
            <option value="417">Luke Campbell</option>
            <option value="418">Luke Skywalker</option>
            <option value="419">Luna</option>
            <option value="420">Lyja</option>
            <option value="421">Mach-IV</option>
            <option value="422">Machine Man</option>
            <option value="423">Magneto</option>
            <option value="424">Magog</option>
            <option value="425">Magus</option>
            <option value="426">Man of Miracles</option>
            <option value="427">Man-Bat</option>
            <option value="428">Man-Thing</option>
            <option value="429">Man-Wolf</option>
            <option value="430">Mandarin</option>
            <option value="431">Mantis</option>
            <option value="432">Martian Manhunter</option>
            <option value="433">Marvel Girl</option>
            <option value="434">Master Brood</option>
            <option value="435">Master Chief</option>
            <option value="436">Match</option>
            <option value="437">Matt Parkman</option>
            <option value="438">Maverick</option>
            <option value="439">Maxima</option>
            <option value="440">Maya Herrera</option>
            <option value="441">Medusa</option>
            <option value="442">Meltdown</option>
            <option value="443">Mephisto</option>
            <option value="444">Mera</option>
            <option value="445">Metallo</option>
            <option value="446">Metamorpho</option>
            <option value="447">Meteorite</option>
            <option value="448">Metron</option>
            <option value="449">Micah Sanders</option>
            <option value="450">Michelangelo</option>
            <option value="451">Micro Lad</option>
            <option value="452">Mimic</option>
            <option value="453">Minna Murray</option>
            <option value="454">Misfit</option>
            <option value="455">Miss Martian</option>
            <option value="456">Mister Fantastic</option>
            <option value="457">Mister Freeze</option>
            <option value="458">Mister Knife</option>
            <option value="459">Mister Mxyzptlk</option>
            <option value="460">Mister Sinister</option>
            <option value="461">Mister Zsasz</option>
            <option value="462">Mockingbird</option>
            <option value="463">MODOK</option>
            <option value="464">Mogo</option>
            <option value="465">Mohinder Suresh</option>
            <option value="466">Moloch</option>
            <option value="467">Molten Man</option>
            <option value="468">Monarch</option>
            <option value="469">Monica Dawson</option>
            <option value="470">Moon Knight</option>
            <option value="471">Moonstone</option>
            <option value="472">Morlun</option>
            <option value="473">Morph</option>
            <option value="474">Moses Magnum</option>
            <option value="475">Mr Immortal</option>
            <option value="476">Mr Incredible</option>
            <option value="477">Ms Marvel II</option>
            <option value="478">Multiple Man</option>
            <option value="479">Mysterio</option>
            <option value="480">Mystique</option>
            <option value="481">Namor</option>
            <option value="482">Namor</option>
            <option value="483">Namora</option>
            <option value="484">Namorita</option>
            <option value="485">Naruto Uzumaki</option>
            <option value="486">Nathan Petrelli</option>
            <option value="487">Nebula</option>
            <option value="488">Negasonic Teenage Warhead</option>
            <option value="489">Nick Fury</option>
            <option value="490">Nightcrawler</option>
            <option value="491">Nightwing</option>
            <option value="492">Niki Sanders</option>
            <option value="493">Nina Theroux</option>
            <option value="494">Nite Owl II</option>
            <option value="495">Northstar</option>
            <option value="496">Nova</option>
            <option value="497">Nova</option>
            <option value="498">Odin</option>
            <option value="499">Offspring</option>
            <option value="500">Omega Red</option>
            <option value="501">Omniscient</option>
            <option value="502">One Punch Man</option>
            <option value="503">One-Above-All</option>
            <option value="504">Onslaught</option>
            <option value="505">Oracle</option>
            <option value="506">Osiris</option>
            <option value="507">Overtkill</option>
            <option value="508">Ozymandias</option>
            <option value="509">Parademon</option>
            <option value="510">Paul Blart</option>
            <option value="511">Penance</option>
            <option value="512">Penance I</option>
            <option value="513">Penance II</option>
            <option value="514">Penguin</option>
            <option value="515">Phantom</option>
            <option value="516">Phantom Girl</option>
            <option value="517">Phoenix</option>
            <option value="518">Plantman</option>
            <option value="519">Plastic Lad</option>
            <option value="520">Plastic Man</option>
            <option value="521">Plastique</option>
            <option value="522">Poison Ivy</option>
            <option value="523">Polaris</option>
            <option value="524">Power Girl</option>
            <option value="525">Power Man</option>
            <option value="526">Predator</option>
            <option value="527">Professor X</option>
            <option value="528">Professor Zoom</option>
            <option value="529">Psylocke</option>
            <option value="530">Punisher</option>
            <option value="531">Purple Man</option>
            <option value="532">Pyro</option>
            <option value="533">Q</option>
            <option value="534">Quantum</option>
            <option value="535">Question</option>
            <option value="536">Quicksilver</option>
            <option value="537">Quill</option>
            <option value="538">Ra's Al Ghul</option>
            <option value="539">Rachel Pirzad</option>
            <option value="540">Rambo</option>
            <option value="541">Raphael</option>
            <option value="542">Raven</option>
            <option value="543">Ray</option>
            <option value="544">Razor-Fist II</option>
            <option value="545">Red Arrow</option>
            <option value="546">Red Hood</option>
            <option value="547">Red Hulk</option>
            <option value="548">Red Mist</option>
            <option value="549">Red Robin</option>
            <option value="550">Red Skull</option>
            <option value="551">Red Tornado</option>
            <option value="552">Redeemer II</option>
            <option value="553">Redeemer III</option>
            <option value="554">Renata Soliz</option>
            <option value="555">Rey</option>
            <option value="556">Rhino</option>
            <option value="557">Rick Flag</option>
            <option value="558">Riddler</option>
            <option value="559">Rip Hunter</option>
            <option value="560">Ripcord</option>
            <option value="561">Robin</option>
            <option value="562">Robin II</option>
            <option value="563">Robin III</option>
            <option value="564">Robin V</option>
            <option value="565">Robin VI</option>
            <option value="566">Rocket Raccoon</option>
            <option value="567">Rogue</option>
            <option value="568">Ronin</option>
            <option value="569">Rorschach</option>
            <option value="570">Sabretooth</option>
            <option value="571">Sage</option>
            <option value="572">Sandman</option>
            <option value="573">Sasquatch</option>
            <option value="574">Sauron</option>
            <option value="575">Savage Dragon</option>
            <option value="576">Scarecrow</option>
            <option value="577">Scarlet Spider</option>
            <option value="578">Scarlet Spider II</option>
            <option value="579">Scarlet Witch</option>
            <option value="580">Scorpia</option>
            <option value="581">Scorpion</option>
            <option value="582">Sebastian Shaw</option>
            <option value="583">Sentry</option>
            <option value="584">Shadow King</option>
            <option value="585">Shadow Lass</option>
            <option value="586">Shadowcat</option>
            <option value="587">Shang-Chi</option>
            <option value="588">Shatterstar</option>
            <option value="589">She-Hulk</option>
            <option value="590">She-Thing</option>
            <option value="591">Shocker</option>
            <option value="592">Shriek</option>
            <option value="593">Shrinking Violet</option>
            <option value="594">Sif</option>
            <option value="595">Silk</option>
            <option value="596">Silk Spectre</option>
            <option value="597">Silk Spectre II</option>
            <option value="598">Silver Surfer</option>
            <option value="599">Silverclaw</option>
            <option value="600">Simon Baz</option>
            <option value="601">Sinestro</option>
            <option value="602">Siren</option>
            <option value="603">Siren II</option>
            <option value="604">Siryn</option>
            <option value="605">Skaar</option>
            <option value="606">Snake-Eyes</option>
            <option value="607">Snowbird</option>
            <option value="608">Sobek</option>
            <option value="609">Solomon Grundy</option>
            <option value="610">Songbird</option>
            <option value="611">Space Ghost</option>
            <option value="612">Spawn</option>
            <option value="613">Spectre</option>
            <option value="614">Speedball</option>
            <option value="615">Speedy</option>
            <option value="616">Speedy</option>
            <option value="617">Spider-Carnage</option>
            <option value="618">Spider-Girl</option>
            <option value="619">Spider-Gwen</option>
            <option value="620">Spider-Man</option>
            <option value="621">Spider-Man</option>
            <option value="622">Spider-Man</option>
            <option value="623">Spider-Woman</option>
            <option value="624">Spider-Woman II</option>
            <option value="625">Spider-Woman III</option>
            <option value="626">Spider-Woman IV</option>
            <option value="627">Spock</option>
            <option value="628">Spyke</option>
            <option value="629">Stacy X</option>
            <option value="630">Star-Lord</option>
            <option value="631">Stardust</option>
            <option value="632">Starfire</option>
            <option value="633">Stargirl</option>
            <option value="634">Static</option>
            <option value="635">Steel</option>
            <option value="636">Stephanie Powell</option>
            <option value="637">Steppenwolf</option>
            <option value="638">Storm</option>
            <option value="639">Stormtrooper</option>
            <option value="640">Sunspot</option>
            <option value="641">Superboy</option>
            <option value="642">Superboy-Prime</option>
            <option value="643">Supergirl</option>
            <option value="644">Superman</option>
            <option value="645">Swamp Thing</option>
            <option value="646">Swarm</option>
            <option value="647">Sylar</option>
            <option value="648">Synch</option>
            <option value="649">T-1000</option>
            <option value="650">T-800</option>
            <option value="651">T-850</option>
            <option value="652">T-X</option>
            <option value="653">Taskmaster</option>
            <option value="654">Tempest</option>
            <option value="655">Thanos</option>
            <option value="656">The Cape</option>
            <option value="657">The Comedian</option>
            <option value="658">Thing</option>
            <option value="659">Thor</option>
            <option value="660">Thor Girl</option>
            <option value="661">Thunderbird</option>
            <option value="662">Thunderbird II</option>
            <option value="663">Thunderbird III</option>
            <option value="664">Thunderstrike</option>
            <option value="665">Thundra</option>
            <option value="666">Tiger Shark</option>
            <option value="667">Tigra</option>
            <option value="668">Tinkerer</option>
            <option value="669">Titan</option>
            <option value="670">Toad</option>
            <option value="671">Toxin</option>
            <option value="672">Toxin</option>
            <option value="673">Tracy Strauss</option>
            <option value="674">Trickster</option>
            <option value="675">Trigon</option>
            <option value="676">Triplicate Girl</option>
            <option value="677">Triton</option>
            <option value="678">Two-Face</option>
            <option value="679">Ultragirl</option>
            <option value="680">Ultron</option>
            <option value="681">Utgard-Loki</option>
            <option value="682">Vagabond</option>
            <option value="683">Valerie Hart</option>
            <option value="684">Valkyrie</option>
            <option value="685">Vanisher</option>
            <option value="686">Vegeta</option>
            <option value="687">Venom</option>
            <option value="688">Venom II</option>
            <option value="689">Venom III</option>
            <option value="690">Venompool</option>
            <option value="691">Vertigo II</option>
            <option value="692">Vibe</option>
            <option value="693">Vindicator</option>
            <option value="694">Vindicator</option>
            <option value="695">Violator</option>
            <option value="696">Violet Parr</option>
            <option value="697">Vision</option>
            <option value="698">Vision II</option>
            <option value="699">Vixen</option>
            <option value="700">Vulcan</option>
            <option value="701">Vulture</option>
            <option value="702">Walrus</option>
            <option value="703">War Machine</option>
            <option value="704">Warbird</option>
            <option value="705">Warlock</option>
            <option value="706">Warp</option>
            <option value="707">Warpath</option>
            <option value="708">Wasp</option>
            <option value="709">Watcher</option>
            <option value="710">Weapon XI</option>
            <option value="711">White Canary</option>
            <option value="712">White Queen</option>
            <option value="713">Wildfire</option>
            <option value="714">Winter Soldier</option>
            <option value="715">Wiz Kid</option>
            <option value="716">Wolfsbane</option>
            <option value="717">Wolverine</option>
            <option value="718">Wonder Girl</option>
            <option value="719">Wonder Man</option>
            <option value="720">Wonder Woman</option>
            <option value="721">Wondra</option>
            <option value="722">Wyatt Wingfoot</option>
            <option value="723">X-23</option>
            <option value="724">X-Man</option>
            <option value="725">Yellow Claw</option>
            <option value="726">Yellowjacket</option>
            <option value="727">Yellowjacket II</option>
            <option value="728">Ymir</option>
            <option value="729">Yoda</option>
            <option value="730">Zatanna</option>
            <option value="731">Zoom</option>
        </select>
        <input type="submit" value="Submit">
    </form>
    <hr/>
    <div>
       <img src='<%=request.getParameter("image")%>'>
       <h2>Superhero</h2> <h3><%=request.getParameter("name")%></h3>
       <h2>Real name</h2> <h3><%=request.getParameter("real-name")%></h3>
       <h2>Place of Birth</h2> <h3><%=request.getParameter("place-of-birth")%></h3>
       <h2>Relatives</h2> <h3><%=request.getParameter("relatives")%></h3>
       <h2>Alter Ego</h2> <h3><%=request.getParameter("alter-egos")%></h3>
       <h2>Race</h2> <h3><%=request.getParameter("race")%></h3>
       <h2>Gender</h2> <h3><%=request.getParameter("gender")%></h3>
       <h2>Height</h2> <h3><%=request.getParameter("height")%></h3>
       <h2>Weight</h2> <h3><%=request.getParameter("weight")%></h3>
       <h2>Occupation</h2> <h3><%=request.getParameter("work")%></h3>
       <h2>intelligence</h2> <h3><%=request.getParameter("power")%></h3>
       <h2>Strength</h2> <h3><%=request.getParameter("power1")%></h3>
       <h2>Speed</h2> <h3><%=request.getParameter("power2")%></h3>
       <h2>Durability</h2> <h3><%=request.getParameter("power3")%></h3>
       <h2>Power</h2> <h3><%=request.getParameter("power4")%></h3>
       <h2>Combat</h2> <h3><%=request.getParameter("power5")%></h3>
    </div>

</body>
</html>
